# Generated by Django 3.2 on 2021-12-16 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriere', models.CharField(default='', max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=400)),
                ('no_likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Main.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='Main.customuser')),
                ('user2', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='Main.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PostUserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=150)),
                ('userName', models.CharField(default='', max_length=150)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.post')),
            ],
        ),
    ]
