# Generated by Django 3.2 on 2021-11-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_userg3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=400)),
                ('no_likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Main.userg3')),
            ],
        ),
        migrations.DeleteModel(
            name='Meme',
        ),
    ]
