# Generated by Django 3.2 on 2021-12-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='Main.customuser')),
                ('user2', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='Main.customuser')),
            ],
        ),
    ]
