# Generated by Django 3.2 on 2021-12-15 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.customuser')),
            ],
        ),
    ]
