# Generated by Django 3.2 on 2021-12-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_postuserlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
