# Generated by Django 3.2 on 2021-12-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
