# Generated by Django 3.2 on 2021-12-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_post_is_liked_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked_by_user',
        ),
    ]
